---
- name: Install Neovim and configure
  hosts: localhost
  become: yes
  tasks:
    - name: Add Neovim PPA repository
      apt_repository:
        repo: "ppa:neovim-ppa/stable"
        state: present

    - name: Update package index
      apt:
        update_cache: yes

    - name: Install Neovim
      apt:
        name: neovim
        state: latest

    - name: Download init.lua file
      become: yes
      shell: wget https://github.com/dwiHard/mydotfile/raw/main/config/neovim/init.lua

    - name: Install build-essential package
      apt:
        name: build-essential
        state: present

    - name: Clean up
      shell: rm -rf init.lua
